/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Halaman;

/**
 *
 * @author muhau
 */

import javax.swing.JComboBox;
import States.Session;
import Controllers.LoginController;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.*;
import Configs.DBConnection;
import Halaman.HalamanUtama;
//import States.Username;

public class HalamanLogin extends javax.swing.JFrame {
    
    /**
     * Creates new form LoginUI
     */
    public HalamanLogin() {
        initComponents();
        
        
        JComboBox comboBox = this.userSelector;
        comboBox.addItem(new MyComboItem(1,"Pembeli"));
        comboBox.addItem(new MyComboItem(2,"Penjual"));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLabel = new javax.swing.JLabel();
        loginBtn = new javax.swing.JButton();
        unameLabel = new javax.swing.JLabel();
        pwdLabel = new javax.swing.JLabel();
        unameBox = new javax.swing.JTextField();
        pwdBox = new javax.swing.JPasswordField();
        userSelector = new javax.swing.JComboBox<>();
        testDBConnectionBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        titleLabel.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        titleLabel.setText("LOGIN ONLINESHOPPING");

        loginBtn.setText("LOGIN");
        loginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBtnActionPerformed(evt);
            }
        });

        unameLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        unameLabel.setText("Username");

        pwdLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        pwdLabel.setText("Password");

        unameBox.setText("");
        unameBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unameBoxActionPerformed(evt);
            }
        });

        pwdBox.setText("");
        pwdBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pwdBoxActionPerformed(evt);
            }
        });

        userSelector.setModel(new javax.swing.DefaultComboBoxModel<>();
            userSelector.addItemListener(new java.awt.event.ItemListener() {
                public void itemStateChanged(java.awt.event.ItemEvent evt) {
                    userSelectorItemStateChanged(evt);
                }
            });
            userSelector.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    userSelectorActionPerformed(evt);
                }
            });

            testDBConnectionBtn.setText("TEST DB CONNECTION");
            testDBConnectionBtn.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    testDBConnectionBtnActionPerformed(evt);
                }
            });

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap(241, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(unameLabel)
                                        .addComponent(pwdLabel))
                                    .addGap(68, 68, 68)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(pwdBox)
                                        .addComponent(unameBox, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(titleLabel, javax.swing.GroupLayout.Alignment.CENTER)
                                .addComponent(userSelector, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(204, 204, 204))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(testDBConnectionBtn)
                            .addGap(53, 53, 53)
                            .addComponent(loginBtn)
                            .addGap(228, 228, 228))))
            );
            layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap(166, Short.MAX_VALUE)
                    .addComponent(titleLabel)
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(unameBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(pwdBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(unameLabel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(pwdLabel)))
                    .addGap(11, 11, 11)
                    .addComponent(userSelector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(loginBtn)
                        .addComponent(testDBConnectionBtn))
                    .addGap(146, 146, 146))
            );

            pack();
        }// </editor-fold>//GEN-END:initComponents

    private void pwdBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pwdBoxActionPerformed
    
    }//GEN-LAST:event_pwdBoxActionPerformed

    private void unameBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unameBoxActionPerformed

    }//GEN-LAST:event_unameBoxActionPerformed

    private void userSelectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userSelectorActionPerformed
          
    }//GEN-LAST:event_userSelectorActionPerformed

    private void userSelectorItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_userSelectorItemStateChanged
        // TODO add your handling code here:
        MyComboItem isPenjual;
        
        //HalamanUtama nextPage = new HalamanUtama();
        try{
        isPenjual = (MyComboItem) evt.getItem();
        System.out.println(isPenjual.getId());}
        catch(Exception ex){
            System.out.println(ex.getMessage());
            Logger.getLogger(HalamanLogin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_userSelectorItemStateChanged

    private void loginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBtnActionPerformed
        
        DBConnection db = new DBConnection();
        Connection conn = null;
        
        String sql = "Select * from login where lg_uname=? and lg_pwd=?";
        try{
        Statement stmt = conn.createStatement();  
        ResultSet res=stmt.executeQuery(sql);  
        System.out.println(res);
            if(res.next()){
                    //JOptionPane.showMessageDialog(null, "Welcome user");
                    HalamanUtama welcome = new HalamanUtama();
                    welcome.setVisible(true);
            }
        }catch(Exception e){
            System.out.println(e);
        }
        
    }//GEN-LAST:event_loginBtnActionPerformed

    private void testDBConnectionBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_testDBConnectionBtnActionPerformed
        // TODO add your handling code here:
        DBConnection db = new DBConnection();
        Connection conn = null;
        
        db.newConnection();
    }//GEN-LAST:event_testDBConnectionBtnActionPerformed

    public void verifyCredentials(){
        //logincontroller.isUnameTrue(input);
        //logincontroller.isPwdTrue(input);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HalamanLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HalamanLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HalamanLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HalamanLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HalamanLogin().setVisible(true);
            }
        });
    }

class MyComboItem {
  private Integer id;
  private String name;

  MyComboItem(Integer id, String name) {
   this.id = id;
   this.name = name;
  }

  public Integer getId() {
   return id;
  }

  public void setId(Integer id) {
   this.id = id;
  }

  public String getName() {
   return name;
  }

  public void setName(String name) {
   this.name = name;
  }

  @Override
  public String toString() {
   return name;
  }
 }


    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton loginBtn;
    private javax.swing.JPasswordField pwdBox;
    private javax.swing.JLabel pwdLabel;
    private javax.swing.JButton testDBConnectionBtn;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JTextField unameBox;
    private javax.swing.JLabel unameLabel;
    private javax.swing.JComboBox<String> userSelector;
    // End of variables declaration//GEN-END:variables
}
