/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

/**
 *
 * @author Raldo Kusuma
 */
public class HalamanUtama extends javax.swing.JFrame implements iHalaman{

    /**
     * Creates new form HalamanUtama
     */
    public HalamanUtama() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        label2 = new java.awt.Label();
        jLabel6 = new javax.swing.JLabel();
        viewProduct = new javax.swing.JButton();
        kotakPencarian = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(743, 63, -1, 249));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(555, 392, -1, 180));

        label2.setFont(new java.awt.Font("Franklin Gothic Book", 3, 24)); // NOI18N
        label2.setText("ONLINE SHOP");
        getContentPane().add(label2, new org.netbeans.lib.awtextra.AbsoluteConstraints(357, 21, -1, -1));
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(743, 392, -1, 180));

        viewProduct.setText("ViewProduct");
        viewProduct.setName(""); // NOI18N
        viewProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewProductActionPerformed(evt);
            }
        });
        getContentPane().add(viewProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(555, 23, 184, 30));

        kotakPencarian.setText("Kotak Pencarian");
        kotakPencarian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kotakPencarianActionPerformed(evt);
            }
        });
        getContentPane().add(kotakPencarian, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 21, 184, 32));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void viewProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewProductActionPerformed
        // TODO add your handling code here:
//        String nama = viewProduct.getName();
        new HalamanLoadingProgress("daftarproduk").setVisible(true);
        this.dispose();
    }//GEN-LAST:event_viewProductActionPerformed

    private void kotakPencarianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kotakPencarianActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kotakPencarianActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HalamanUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HalamanUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HalamanUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HalamanUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new HalamanUtama().setVisible(true);
        });
    }

    @Override
    public void showPage() {
 
    }

    @Override
    public void hidePage() {
    
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField kotakPencarian;
    private java.awt.Label label2;
    private javax.swing.JButton viewProduct;
    // End of variables declaration//GEN-END:variables
}
